facebook:
  client_id: ${FB_CLIENT_ID}
  client_secret: ${FB_CLIENT_SECRET}
  api_base_url: https://graph.facebook.com
  default_scopes:
    - pages_read_engagement
    - pages_read_user_content
    - instagram_basic
    - instagram_manage_comments

twitter:
  api_key: ${TWITTER_API_KEY}
  api_key_secret: ${TWITTER_API_SECRET}
  bearer_token: ${TWITTER_BEARER_TOKEN}
  api_base_url: https://api.twitter.com/2
  default_scopes:
    - tweet.read
    - users.read
    - offline.access

linkedin:
  client_id: ${LINKEDIN_CLIENT_ID}
  client_secret: ${LINKEDIN_CLIENT_SECRET}
  api_base_url: https://api.linkedin.com/v2
  default_scopes:
    - r_liteprofile
    - r_organization_social
    - w_organization_social
    - offline_access

youtube:
  client_id: ${YOUTUBE_CLIENT_ID}
  client_secret: ${YOUTUBE_CLIENT_SECRET}
  api_base_url: https://www.googleapis.com/youtube/v3
  default_scopes:
    - youtube.readonly
    - youtube.force-ssl

tiktok:
  client_key: ${TIKTOK_CLIENT_KEY}
  client_secret: ${TIKTOK_CLIENT_SECRET}
  api_base_url: https://api.tiktok.com
  default_scopes: []  # to be determined 